
<?php
    session_start();
    $cadastro = "";
    // if (isset($_POST['cadastro'])) { 
    //   $cadastro = $_POST['cadastro'];
    //   unset($_POST['cadastro']);
    // } else {
    //   $cadastro = "";
    // }
    var_dump(isset($_GET['cadastro']));
    // var_dump($_GET['cadastro']);
?>
<?php if (!empty($cadastro)) { ?>
  <div class="alert alert-warning alert-dismissible fade show" role="alert">
    <strong>Holy guacamole!</strong> You should check in on some of those fields below.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<?php } ?>
<div class="container mt-4">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Descrição</th>
          <th scope="col">Valor</th>
          <th scope="col">Tipo</th>
          <th scope="col">Data</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <?php foreach($this->view->financa as $financa) { ?>
          <tr>
            <th scope="row"><?= $financa['id'] ?></th>
            <td><?= $financa['descricao'] ?></td>
            <td><?= $financa['valor'] ?></td>
            <td><?= $financa['tipo'] ?></td>
            <td><?= $financa['dataFinanca'] ?></td>
          </tr>

        <?php } ?>
      </tbody>
    </table>
    <a href="/financa/novo" class="btn btn-primary">Cadastrar</a>
</div>