
<?php
    session_start();
    $msg = isset($_GET['save']) ? $_GET['save']: '';
?>
<?php if (!empty($msg)) { ?>
  <div class="alert alert-success alert-dismissible fade show" role="alert">
    <strong>Aviso!</strong> Finança salva com sucesso !!!.
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<?php } ?>

<div class="container mt-4">
    <table class="table" id="myTable">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Descrição</th>
          <th scope="col">Valor</th>
          <th scope="col">Tipo</th>
          <th scope="col">Data</th>
        </tr>
      </thead>
      <tbody class="table-group-divider">
        <?php foreach($this->view->financa as $financa) { ?>
          <tr>
            <th scope="row"><?= $financa['id'] ?></th>
            <td><?= $financa['descricao'] ?></td>
            <td><?= $financa['valor'] ?></td>
            <td><?= $financa['tipo'] ?></td>
            <td><?= $financa['dataFinanca'] ?></td>
          </tr>

        <?php } ?>
      </tbody>
    </table>
    <a href="/financa/novo" class="btn btn-primary">Cadastrar</a>
</div>
<script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.12.1/js/jquery.dataTables.js"></script>

<script>
  $(document).ready( function () {
      $('#myTable').DataTable(
        {
          "language": {
            "paginate": {
              "previous": "Anterior",
              "next" : "Próximo",
            },
            "search" : "Pesquisar",
            "show" : "mostrar"
          }
        }
      );
  } );
</script>