<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <title>Finança TCC</title>
</head>
<body>

    <?= $this->content() ?>
    
<script>
    $(document).ready(function(){
        $(this).on('keypress',function(e) {
            if(e.which == 13) {
                e.preventDefault();
            }
        });
        let verif = 0;
       
        $("#confirmarSenha").keyup(function(){
            if ($("#senha").val() != this.value){
                $("#confirmarSenha").addClass("is-invalid");
            } else {
                $("#confirmarSenha").removeClass("is-invalid");
                $("#confirmarSenha").addClass("is-valid");
            }
        });

        $("#usuario").blur(function(){

            if ($("#usuario").val() == ""){
                $("#usuario").addClass("is-invalid");
                $("#validUsuario").html("Campo obrigatório");
            } else {
                $.ajax({
                type: "POST",
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').last().attr('content'))},
                url: '/verificarUsuario',
                data: {usuario: $("#usuario").val()},
                success: function(data) {
                    if (data.count > 0 ){
                        $("#usuario").addClass("is-invalid");
                        $("#validUsuario").html("Usuário já existe");
                        $("#cadastrar").attr("disabled","true");
                    } else {
                        $("#cadastrar").removeAttr("disabled","false");
                        $("#usuario").removeClass("is-invalid");
                        $("#usuario").addClass("is-valid");
                    }
                    
                }
                });
                
            }
           

            
        });

        $("#senha").blur(function(){
            if ($("#senha").val() == ""){
                $("#senha").addClass("is-invalid");
            } else {
                $("#senha").removeClass("is-invalid");
                $("#senha").addClass("is-valid");
            }
        });

        $("#email").blur(function(){
            if ($("#email").val() == ""){
                $("#email").addClass("is-invalid");
                $("#validEmail").html("Campo obrigatório");
            } else {
                $.ajax({
                type: "POST",
                beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').last().attr('content'))},
                url: '/verificarEmail',
                data: {email: $("#email").val()},
                success: function(data) {
                    console.log(data);
                    if (data.count > 0 ){
                        $("#email").addClass("is-invalid");
                        $("#validEmail").html("Email já existe");
                        $("#cadastrar").attr("disabled","true");
                    } else {
                        $("#cadastrar").removeAttr("disabled","false");
                        $("#email").removeClass("is-invalid");
                        $("#email").addClass("is-valid");
                    }
                    
                }
                });
            }
        });

        $("#cadastrar").click(function(event){
            

            if ($("#usuario").val() == "") {
                $("#usuario").addClass("is-invalid");
            } else {
                verif = verif + 1;
                $("#usuario").removeClass("is-invalid");
                $("#usuario").addClass("is-valid");
            }

            if ($("#senha").val() == "") {
                $("#senha").addClass("is-invalid");
            } else {
                verif = verif + 1;
                $("#senha").removeClass("is-invalid");
                $("#senha").addClass("is-valid");
            }

            if ($("#confirmarSenha").val() == "") {
                $("#confirmarSenha").addClass("is-invalid");
            } else {
                verif = verif + 1;
                $("#confirmarSenha").removeClass("is-invalid");
                $("#confirmarSenha").addClass("is-valid");
            }

            if ($("#email").val() == "") {
                $("#email").addClass("is-invalid");
            } else {
                verif = verif + 1;
                $("#email").removeClass("is-invalid");
                $("#email").addClass("is-valid");
            }

            if(verif < 4){
                event.preventDefault();
            }
        });
       
        
    });
</script>
</body>
</html>