<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.12.1/css/jquery.dataTables.css">
    <title>Finança TCC</title>
</head>
<body>
<nav class="navbar bg-light fixed-top">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
          <div class="offcanvas-header">
            <h5 class="offcanvas-title" id="offcanvasNavbarLabel">Financas</h5>
            <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
          </div>
          <div class="offcanvas-body">
            <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="#">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#">Link</a>
              </li>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Dropdown
                </a>
                <ul class="dropdown-menu">
                  <li><a class="dropdown-item" href="#">Action</a></li>
                  <li><a class="dropdown-item" href="#">Another action</a></li>
                  <li>
                    <hr class="dropdown-divider">
                  </li>
                  <li><a class="dropdown-item" href="#">Something else here</a></li>
                </ul>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
          </div>
        </div>
        <a class="navbar-brand" href="/home"><?=  $_SESSION['usuario'] ?></a>
      </div>
    </nav>
    <?= $this->content() ?>
</body>
<script>
  $(document).ready(function(){
    $("#cadastrarFinanca").on('keypress',function(e) {
        if(e.which == 13) {
            e.preventDefault();
        }
    });

    $("#valor").blur(function(){
      if(this.value != "") {
        if(this.value >= 0 ) {
          $("#despesa").remove();
        } else {
          $("#receita").remove();
        }
      }
    });
    
    $("#salvarFinanca").on("click", function (event){
      
      let valid  = 0;

      if($("#descricao").val() != "") {
        valid = valid + 1;
        $("#descricao").removeClass("is-invalid");
      } else {
        $("#validDescricao").html("Campo obrigatório");
        $("#descricao").addClass("is-invalid");
      }

      if($("#valor").val() != "") {
        valid = valid + 1;
        $("#valor").removeClass("is-invalid");
      } else {
        $("#validValor").html("Campo obrigatório");
        $("#valor").addClass("is-invalid");

      }

      if($("#tipoFinanca").val() != "") {
        valid = valid + 1;
        $("#tipoFinanca").removeClass("is-invalid");
      } else {
        $("#validTipo").html("Campo obrigatório");
        $("#tipoFinanca").addClass("is-invalid");

      }

      if($("#data").val() != "") {
        valid = valid + 1;
        $("#data").removeClass("is-invalid");
      } else {
        $("#validData").html("Campo obrigatório");
        $("#data").addClass("is-invalid");
      }

      if (valid < 4) {
        event.preventDefault();
      }

    });

      //fetch new URL
    //refineURL() gives you the freedom to alter the URL string based on your needs. 
    var myNewURL = refineURL();

    //here you pass the new URL extension you want to appear after the domains '/'. Note that the previous identifiers or "query string" will be replaced. 
    window.history.pushState("object or string", "Title", "/" + myNewURL );


    //Helper function to extract the URL between the last '/' and before '?' 
    //If URL is www.example.com/one/two/file.php?user=55 this function will return 'file.php' 
    //pseudo code: edit to match your URL settings  

    function refineURL()
    {
        //get full URL
        var currURL= window.location.href; //get current address
        console.log(currURL);
        //Get the URL between what's after '/' and befor '?' 
        //1- get URL after'/'
        var afterDomain= currURL.substring(currURL.lastIndexOf('/') + 1);
        //2- get the part before '?'
        var beforeQueryString= afterDomain.split("?")[0];  
    
        return beforeQueryString;     
    }
    
  });
</script>
</html>